# Apache HTTP Server main configuration file

DefaultRuntimeDir ${APACHE_RUN_DIR}
PidFile ${APACHE_PID_FILE}
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5

User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}

HostnameLookups Off
ErrorLog ${APACHE_LOG_DIR}/error.log
LogLevel warn

# Include module configuration
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

# Include ports to listen on
Listen 80

<Directory />
    Options FollowSymLinks
    AllowOverride None
    Require all denied
</Directory>

# Configuration files
IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*.conf

# Charset module
AddDefaultCharset UTF-8
